### ISSUE TITLE
Error on running build

### ISSUE THREAD

**Issue by jamesjtong** [anodynos/urequire-rc-rxjs5-custom-build#1]
Running into the following error on running grunt
`
Running "urequire:build" (urequire) task
  [uRequire/process/Build] ERRor:  #0: ResourceConverterError
  Error: Error converting Module 'urequire-rc-rxjs5-custom-build.js6' with ResourceConverter 'babeljs' @ step convert.
  [uRequire/process/Build] ERRor: nested #1: SyntaxError
      SyntaxError: unknown: Unexpected token (18:41)`

**Comment by anodynos** [comment]
Hi & sorry for delayed response - can you share some details so I can have a look (windows/linux/mac node/npm versions)?

**Comment by anodynos** [comment]
Yeah, dont worry about it - the github version is cocked up, I'll fix it

**Comment by anodynos** [comment]
It's fixed now - sorry for this... That's what you get when you'e too busy to add CI :-/
